server:
  port: 1007
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: qweqwe
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      # 指定nacos server的地址
      discovery:
        server-addr: localhost:8848
       # 指定namespace
       # namespace: 3440c980-9fc9-455c-9858-9010b9daa703
       # NJ
       # 指定集群名称
        cluster-name: BJ
        metadata:
         instance: c
         haha: hehe
         version: v1
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          # destination: stream-test-topic
          destination: add-bonus
          # 如果用的是RocketMQ，一定要设置
          # 如果用的其他MQ，可留空
          group: binder-group
        #my-input:
        #  destination: stream-my-topic
          # 如果用的是RocketMQ，一定要设置
          # 如果用的其他MQ，可留空
        #  group: my-group
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      # 抽样率，默认是0.1 (10%)
      probability: 1.0
#rocketmq:
#  name-server: 127.0.0.1:9876
logging:
  level:
    com.alibaba.nacos: error
    org.springframework.cloud.sleuth: debug

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
